# Generated by Django 3.2.5 on 2022-04-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HX', '0006_auto_20220411_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hx',
            old_name='Tcin',
            new_name='T1',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Tcold',
            new_name='T2',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Tcout',
            new_name='T3',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Thin',
            new_name='T4',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Thot',
            new_name='T5',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Thout',
            new_name='T6',
        ),
    ]
